### ISSUE TITLE
Clicking create configuration file throws error

### ISSUE THREAD

**Issue by karlhenselin** [DataDog/datadog-for-intellij-platform#36]
Clicking create configuration file

![Image](https://github.com/user-attachments/assets/db18602d-a73c-429c-9cba-8273dfeb268c)

got error

java.lang.IllegalStateException: Failed to create new config file
	at com.datadog.intellij.staticAnalysis.StaticAnalysisOnboarding.createNewConfigFile(StaticAnalysisOnboarding.kt:56)
	at com.datadog.intellij.staticAnalysis.StaticAnalysisOnboarding$NotificationProvider$createYamlFilePanel$1$1.invoke(StaticAnalysisOnboarding.kt:294)
	at com.datadog.intellij.staticAnalysis.StaticAnalysisOnboarding$NotificationProvider$createYamlFilePanel$1$1.invoke(StaticAnalysisOnboarding.kt:293)
	at com.datadog.intellij.toolkit.ApplicationExtensionKt.executeOnPooledThreadUnlessIsUnitTestMode$lambda$0(ApplicationExtension.kt:10)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

## What versions of software are you using?
- Operating System: windows 11
- IDE version: [ IntelliJ IDEA Community] 
- Datadog plugin version: [1.4.7]

**Comment by abrooksv** [comment]
Thank you for the bug report. 

I notice that your version is out of date. The latest is 1.6.0 but requires IntelliJ 2023.3 or newer to work. Are you able to try a newer IDE version and the latest plugin version?

**Comment by karlhenselin** [comment]
I upgraded, but I also had clicked the don't ask me again. Is there a way to reset the don't ask me again so that it asks me?

**Comment by abrooksv** [comment]
Not through the UI, you need to locate the settings files manually today:

1. Locate the IDE's application settings. For Windows it should be  `%APPDATA%\JetBrains\<product><version>` ([docs](https://www.jetbrains.com/help/idea/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#config-directory))
2. Open the file `other.xml`
3. Delete the component named `DatadogStaticAnalyzerSettings`

It should look something like this:
```
  <component name="DatadogStaticAnalyzerSettings">
    <promotion-ignored>
      <language id="JAVA" />
    </promotion-ignored>
  </component>
```

**Comment by karlhenselin** [comment]
Thanks much!
I was able to do that, and it works now!
Thanks!
